[project]
name = "spot"
version = "0.1.0"
requires-python = "==3.13.8"
dependencies = [
    "fastapi>=0.121.1",
    "httpx>=0.28.1",
    "pynput>=1.8.1",
    "pyqt6>=6.10.0",
    "python-dispatch>=0.2.2",
    "uvicorn>=0.38.0",
    "websocket-client>=1.9.0",
    "websockets>=15.0.1",
]
